# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  ##
  # Configure VM
  ##

  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "web01"
  config.disksize.size = "500GB"

  config.vm.provider "virtualbox" do |v|
     v.customize [
                        "modifyvm", :id,
                        "--memory", "4096",
						"--vram", "32"
                 ]
	 v.gui = true
  end
  
  ##
  # Shared Folder is on the Host the Vagrant Folder where the VagrantFile is located. In the Guest it is /vagrant from the root file system.
  ## 
  ##
  # Shared Folder is on the Host the Vagrant Folder where the VagrantFile is located. In the Guest it is /vagrant from the root file system.
  ## 
  config.vm.synced_folder "share", "/vagrant", owner: "vagrant",
    group: "vagrant", mount_options: ["uid=1234", "gid=1234"]

  ##
  #Ansible will be automatically installed by Vagrant. After vagrant up. Run vagrant provision to run the ansible playbook.yml
  ##
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.install_mode = "pip"
	ansible.version = "latest"
  end
  
  ##
  #Ansible will be automatically installed by Vagrant. After vagrant up. Run vagrant provision to run the ansible playbook.yml
  ##
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "ansible/playbook.yml"
    ansible.install_mode = "default"
  end
end
