---
- name: Add Docker pgp key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.0.asc
    state: present
    
- apt_repository:
    repo: deb http://repo.mongodb.org/apt/debian stretch/mongodb-org/4.0 main
    state: present

- apt:
    update_cache: yes
  
- name: COMMON | Install basic packages
  package: name={{ item }} state=absent
  with_items:
    - docker
    - docker-engine
    - docker.io

- name: COMMON | Install basic packages
  package: name={{ item }} state=present
  with_items:
    - docker-ce
